"""
Django settings for config project.
Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path
import os

# --- Paths ---
BASE_DIR = Path(__file__).resolve().parent.parent

from dotenv import load_dotenv
load_dotenv(BASE_DIR / ".env")

# --- Seguridad (solo dev) ---
SECRET_KEY = "django-insecure-fp-p1v73$)v$)bbr*0o7=)v6-bgfs2eyyvqbchmu^bz^an1ax9"
DEBUG = True

# --- Hosts / CSRF (incluye ngrok) ---
ALLOWED_HOSTS = ["127.0.0.1", "localhost", "usuarios.autocs.cl", ".ngrok-free.app"]
CSRF_TRUSTED_ORIGINS = [
    "https://usuarios.autocs.cl",
    "https://*.ngrok-free.app",  # admite cualquier subdominio ngrok
]
# Si sirves detrás de proxy/ingress que termina SSL (ngrok, nginx, etc.)
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# --- Apps ---
INSTALLED_APPS = [
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "core.apps.CoreConfig",

    # Requerido por allauth
    "django.contrib.sites",

    # Allauth
    "allauth",
    "allauth.account",
    "allauth.socialaccount",
    "allauth.socialaccount.providers.google",
    "allauth.socialaccount.providers.microsoft",
    
]

SITE_ID = 1

# --- Auth / Allauth ---
AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",                    # admin, etc.
    "allauth.account.auth_backends.AuthenticationBackend",         # allauth
]

# Django 5.2 / allauth ≥ 65.0
ACCOUNT_LOGIN_METHODS = {"username"}  # puedes usar {"email"} o {"username", "email"}
ACCOUNT_SIGNUP_FIELDS = ["email", "username*", "password1*", "password2*"]


# A dónde van las rutas de login/logout (usamos allauth directamente)
LOGIN_URL = "account_login"       # /accounts/login/
LOGIN_REDIRECT_URL = "account"
# Asegura que logout (allauth) siempre vuelva a landing
LOGOUT_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_REDIRECT_URL = "/"
ACCOUNT_LOGOUT_ON_GET = True

# --- Middleware ---
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",  # requerido por allauth
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

# --- Templates (único bloque, sin duplicados) ---
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # carpeta global de templates
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",  # necesario para allauth
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.global_user",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# --- Base de datos (rápido: SQLite) ---
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "saas20",
        "USER": "postgres",
        "PASSWORD": "Luquitasx8", 
        "HOST": "127.0.0.1",
        "PORT": "5432",
    }
}

# Usar SQLite para tests si no se configura lo contrario
import os as _os
if _os.getenv("USE_SQLITE_FOR_TESTS", "1") == "1":
    DATABASES["default"].setdefault("TEST", {})
    DATABASES["default"]["TEST"]["ENGINE"] = "django.db.backends.sqlite3"
# --- Validación de contraseñas ---
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# --- Internacionalización ---
LANGUAGE_CODE = "es"
TIME_ZONE = "America/Santiago"
USE_I18N = True
USE_TZ = True

# --- Estáticos / Media ---
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]  # crea BASE_DIR/static cuando la uses
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# --- Clave por defecto de PK ---
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"



PUBLIC_BASE_URL = os.getenv("PUBLIC_BASE_URL", "http://127.0.0.1:8000")

# --- Mercado Pago (desde variables de entorno) ---
MP_ACCESS_TOKEN   = os.getenv("MP_ACCESS_TOKEN", "TEST-6374217171817553-081910-f3bad05eb56b43556b4a245931a525d4-171920179")
MP_PUBLIC_KEY     = os.getenv("MP_PUBLIC_KEY", "TEST-18e1ab41-da59-4022-972b-e8863e530e5c")
MP_WEBHOOK_SECRET = os.getenv("MP_WEBHOOK_SECRET", "dev-secret")
# En local déjalo vacío; con ngrok exporta:
#   MP_WEBHOOK_URL="https://<ngrok>/webhooks/mercadopago"
MP_WEBHOOK_URL    = os.getenv("MP_WEBHOOK_URL", "")

# --- API bridge Frontend (NextAuth) → Django ---
FRONTEND_SYNC_API_KEY = os.getenv("FRONTEND_SYNC_API_KEY", "dev-frontend-sync")

# Detección rápida de modo sandbox/test para depuración
MP_IS_TEST = str(MP_ACCESS_TOKEN).startswith("TEST-") or str(MP_PUBLIC_KEY).startswith("TEST-")
